global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'coturn-admin'
    static_configs:
      - targets: ['admin:8081']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'coturn-nodes'
    static_configs:
      - targets: ['coturn-node:8082']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
