services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development

  coturn-node:
    build:
      context: .
      dockerfile: apps/coturn-node/Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development

  nexrtc-gateway:
    build:
      context: .
      dockerfile: apps/nexrtc-gateway/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgres://coturn:coturn@postgres:5432/coturn_db
      - JWT_SECRET=supersecretjwtkey  # gerekiyorsa
      - TURN_API_URL=http://coturn-node:8100  # gerekiyorsa

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: coturn
      POSTGRES_PASSWORD: coturn
      POSTGRES_DB: coturn_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
