apiVersion: apps/v1
kind: Deployment
metadata:
  name: coturn-deployment
  namespace: coturn-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coturn-node
  template:
    metadata:
      labels:
        app: coturn-node
    spec:
      containers:
      - name: coturn-node
        image: coturn-node:latest
        ports:
        - containerPort: 3478
          protocol: UDP
        - containerPort: 5349
          protocol: TCP
        - containerPort: 8080
        env:
        - name: ADMIN_PUBSUB_URL
          value: "ws://admin-svc:9001"
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: coturn-svc
  namespace: coturn-system
spec:
  selector:
    app: coturn-node
  type: LoadBalancer
  ports:
  - name: turn-udp
    port: 3478
    protocol: UDP
  - name: turns-tcp
    port: 5349
    protocol: TCP
